@echo off
echo Starting Backend...
start "HackStack Backend" cmd /k "cd backend && npm run dev"
echo Starting Frontend...
start "HackStack Frontend" cmd /k "cd frontend && npm run dev"
echo Happy Hacking!
